
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 6;
  public static final int IZQ = 3;
  public static final int LETTER = 9;
  public static final int DER = 4;
  public static final int NUMBER = 10;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int PRODUCT = 7;
  public static final int error = 1;
  public static final int DIVISION = 8;
  public static final int SEMICOLON = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "IZQ",
  "DER",
  "PLUS",
  "MINUS",
  "PRODUCT",
  "DIVISION",
  "LETTER",
  "NUMBER"
  };
}

